version: '3.0'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch:/data:cached
    ports:
      - "9200:9200"
      - "9300:9300"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/blog_api
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - db
      - elasticsearch
    environment:
      PG_PASSWORD: password
      ELASTICSEARCH_URL: 'http://elasticsearch:9200'

volumes:
  elasticsearch:
    driver: local
