version: '3.0'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: always

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/blog_api
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - db
    environment:
      PG_PASSWORD: password
